### ISSUE TITLE
profile problem

### ISSUE THREAD

**Issue by cnzhanj** [msr-fiddle/pipedream#16]
@deepakn94 it looks like that the container doesn't support NVIDIA GPU K40c, So, I decided modify the pytorch source code according pre_hook.patch, But I did not success:
1. After modify the code, I should set USE_NCCL = OFF? I did this and compile successfuly.
2. Is there any Points to care about when I use pytorch source code instead container? Because When I run image_classification in profiler, the output error is 

=> creating model 'resnet50'
Collecting profile...

Total accounted time: 2364.255 ms
Traceback (most recent call last):
  File "main.py", line 569, in <module>
    main()
  File "main.py", line 283, in main
    os.path.join(args.profile_directory, args.arch))
  File "main.py", line 115, in create_graph
    output = model(input)
  File "/seu_share/home/zhanjun/.conda/envs/pipetorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 571, in __call__
    result = self.forward(*input, **kwargs)
  File "/seu_share/home/zhanjun/.conda/envs/pipetorch/lib/python3.6/site-packages/torchvision/models/resnet.py", line 207, in forward
    x = torch.flatten(x, 1)
TypeError: flatten(): argument 'input' (position 1) must be Tensor, not TensorWrapper

Thank you!

**Comment by deepakn94** [comment]
What version of PyTorch / torchvision is this using?

**Comment by cnzhanj** [comment]
Thank you, I change torchvision from 0.4 to 0.2.1,  the error disappears. However, when I profile vgg16 and alexnet, there is another error occurs:

root@gpu02:/data/2020/pipedream/profiler/image_classification# python main.py -a vgg16 -b 64 --data_dir /data/DL/imagenet/
=> creating model 'vgg16'
Collecting profile...
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs0
Traceback (most recent call last):
  File "main.py", line 576, in <module>
    main()
  File "main.py", line 266, in main
    per_layer_times, data_time = profile_train(train_loader, model, criterion, optimizer)
  File "main.py", line 352, in profile_train
    output = model(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torchvision/models/vgg.py", line 42, in forward
    x = self.features(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/container.py", line 97, in forward
    input = module(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "../torchmodules/torchprofiler/profiling.py", line 132, in forward_wrapper
    result = this_profiler.forward_original_methods[self](*input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 339, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 1 does not equal 0 (while checking arguments for cudnn_convolution)


root@gpu02:/data/2020/pipedream/profiler/image_classification# python main.py -a alexnet -b 64 --data_dir /data/DL/imagenet/
=> creating model 'alexnet'
Collecting profile...
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs0
Traceback (most recent call last):
  File "main.py", line 576, in <module>
    main()
  File "main.py", line 266, in main
    per_layer_times, data_time = profile_train(train_loader, model, criterion, optimizer)
  File "main.py", line 352, in profile_train
    output = model(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torchvision/models/alexnet.py", line 43, in forward
    x = self.features(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/container.py", line 97, in forward
    input = module(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "../torchmodules/torchprofiler/profiling.py", line 132, in forward_wrapper
    result = this_profiler.forward_original_methods[self](*input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 339, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 1 does not equal 0 (while checking arguments for cudnn_convolution)



And, resnet , densenet and others have no errors, Is it related to the model class?

**Comment by deepakn94** [comment]
How many GPUs are you using to profile? Are you prefixing the profiling command with `CUDA_VISIBLE_DEVICES=0` or something similar?

**Comment by cnzhanj** [comment]
Ok, thank you!

**Comment by heguangxin** [comment]
> 

i got the same question and i am using py3.8 + torchvision0.9. Any advice? Thanks a lot!!
