### ISSUE TITLE
Does it work for a detection network with branches?

### ISSUE THREAD

**Issue by ymsdu2004** [msr-fiddle/pipedream#17]
hi, i notice the implemetation for image classification in pipedream, but not sure it also works for object detection network?

**Comment by deepakn94** [comment]
It should work. However, you will need to integrate your model with the profiler, code generator and runtime to get results.

I can help you with these steps if you want to take a stab at this.

**Comment by ymsdu2004** [comment]
> It should work. However, you will need to integrate your model with the profiler, code generator and runtime to get results.
> 
> I can help you with these steps if you want to take a stab at this.

Thank you very much, I am trying to use 'mmdetection' (https://github.com/open-mmlab/mmdetection) as the detection framework of pipedream. As you said, I have added the image detection entry for profiler, and then I have to modify optimizer and runtime, I will ask you for help if needed

**Comment by ymsdu2004** [comment]
hi， I encountered some problems when generating graphs for image detection，it seems caused by graph creator's forward hook，do you have any suggestions for solving these problems?

`Traceback (most recent call last):
  File "test.py", line 246, in <module>
    os.path.join(args.profile_directory, cfg.model.type))
  File "test.py", line 48, in create_graph
    output = model(imgs, img_metas, **model_input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 510, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/admin/pipedream/profiler/image_detection/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/admin/pipedream/profiler/image_detection/mmdetection/mmdet/models/detectors/base.py", line 89, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/admin/pipedream/profiler/image_detection/mmdetection/mmdet/models/detectors/htc.py", line 213, in forward_train
    rpn_outs = self.rpn_head(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 510, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/admin/pipedream/profiler/image_detection/mmdetection/mmdet/models/anchor_heads/anchor_head.py", line 92, in forward
    return multi_apply(self.forward_single, feats)
  File "/home/admin/pipedream/profiler/image_detection/mmdetection/mmdet/core/utils/misc.py", line 24, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/admin/pipedream/profiler/image_detection/mmdetection/mmdet/models/anchor_heads/rpn_head.py", line 35, in forward_single
    x = F.relu(x, inplace=True)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 935, in relu
    result = torch.relu_(input)
TypeError: relu_(): argument 'input' (position 1) must be Tensor, not TensorWrapper`

**Comment by deepakn94** [comment]
If possible, can you replace all instances of PyTorch's functional API with the corresponding module call (for example, replace `F.relu()` with `torch.nn.relu`).

**Comment by ymsdu2004** [comment]
@deepakn94 i have another problem, it seems the the optimizer_graph_hierarchical.py falling into an infinite loop when executing "graph.py:antichain_dag". here is my profile results:http://sanzhi-ym.oss-cn-hangzhou-zmf.aliyuncs.com/temp%2FFCOS.tar.gz
