### ISSUE TITLE
does branch mechanism has not been implemented yet？

### ISSUE THREAD

**Issue by ymsdu2004** [msr-fiddle/pipedream#18]
`Traceback (most recent call last):
  File "main_with_runtime.py", line 579, in <module>
    main()
  File "main_with_runtime.py", line 129, in main
    module = importlib.import_module(args.module)
  File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/admin/pipedream/runtime/image_classification/models/inceptionv3/gpus=2/__init__.py", line 1, in <module>
    from .inceptionv3 import Inceptionv3Partitioned
  File "/home/admin/pipedream/runtime/image_classification/models/inceptionv3/gpus=2/inceptionv3.py", line 2, in <module>
    from .stage0 import Stage0
  File "/home/admin/pipedream/runtime/image_classification/models/inceptionv3/gpus=2/stage0.py", line 24
    self.layer19 = torch.nn.Branch 3`

here is generated stages's code， it seems not legal python code：

`class Stage0(torch.nn.Module):
    def __init__(self):
        super(Stage0, self).__init__()
        self.layer2 = torch.nn.Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), bias=False)
        self.layer3 = torch.nn.BatchNorm2d(32, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        self.layer4 = torch.nn.ReLU(inplace=True)
        self.layer5 = torch.nn.Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), bias=False)
        self.layer6 = torch.nn.BatchNorm2d(32, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        self.layer7 = torch.nn.ReLU(inplace=True)
        self.layer8 = torch.nn.Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        self.layer9 = torch.nn.BatchNorm2d(64, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        self.layer10 = torch.nn.ReLU(inplace=True)
        self.layer11 = torch.nn.MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
        self.layer12 = torch.nn.Conv2d(64, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.layer13 = torch.nn.BatchNorm2d(80, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        self.layer14 = torch.nn.ReLU(inplace=True)
        self.layer15 = torch.nn.Conv2d(80, 192, kernel_size=(3, 3), stride=(1, 1), bias=False)
        self.layer16 = torch.nn.BatchNorm2d(192, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        self.layer17 = torch.nn.ReLU(inplace=True)
        self.layer18 = torch.nn.MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
        self.layer19 = torch.nn.Branch 3
        self.layer20 = torch.nn.Branch 2
        self.layer21 = torch.nn.Branch 1
        self.layer22 = torch.nn.Branch 0
        self.layer24 = torch.nn.Branch 7
        self.layer25 = torch.nn.Branch 6
        self.layer26 = torch.nn.Branch 5
        self.layer27 = torch.nn.Branch 4
        self.layer29 = torch.nn.Branch 9
        self.layer30 = torch.nn.Branch 8
        self.layer31 = torch.nn.Branch 11
        self.layer32 = torch.nn.Branch 10
        self.layer34 = torch.nn.MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
        self.layer35 = torch.nn.Branch 13
        self.layer36 = torch.nn.Branch 12`

**Comment by deepakn94** [comment]
It seems that your profile has a module called `Branch` that PipeDream's code generator doesn't know how to code generate. Things should work if you put some logic in `convert_graph_to_model.py` to handle this.
