### ISSUE TITLE
Invalid shape when running example workflow

### ISSUE THREAD

**Issue by gth828r** [msr-fiddle/pipedream#3]
Hello,

I am walking through the example workflow, and I am hitting an issue when running:
```
# python main_with_runtime.py --module models.vgg16.gpus=4 -b 64 --data_dir /mnt --rank 0 --master_addr 127.0.0.1 --config_path models/vgg16/gpus=4/hybrid_conf.json
Traceback (most recent call last):
  File "main_with_runtime.py", line 578, in <module>
    main()
  File "main_with_runtime.py", line 149, in main
    output_tensors = stage(*tuple(input_tensors))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/pipedream/runtime/image_classification/models/vgg16/gpus=4/stage1.py", line 60, in forward
    out16 = out14.view(out15)
RuntimeError: shape '[64]' is invalid for input of size 1605632
```

My environment is a single docker container running on a single 4 GPU machine configured following the instructions in https://github.com/msr-fiddle/pipedream#setup.  The commands that I ran were:
```
cd profiler/image_classification
CUDA_VISIBLE_DEVICES=0 python main.py -a vgg16 -b 64 --data_dir /mnt
cd ../../optimizer/
python optimizer_graph_hierarchical.py -f ../profiler/image_classification/profiles/vgg16/graph.txt -n 4 --activation_compression_ratio 1 -o vgg16_partitioned
python convert_graph_to_model.py -f vgg16_partitioned/gpus=4.txt -n VGG16Partitioned -a vgg16 -o ../runtime/image_classification/models/vgg16/gpus=4 --stage_to_num_ranks 0:3,1:1
cd ../runtime/image_classification/
python main_with_runtime.py --module models.vgg16.gpus=4 -b 64 --data_dir /mnt --rank 0 --master_addr 127.0.0.1 --config_path models/vgg16/gpus=4/hybrid_conf.json
```

I ran through a similar issue trying to set up a model of alexnet with 4 GPUs using a batch size of 256, except that the runtime error complained about a shape of '[256]' instead.  I can provide details on what I ran there if it is useful.

Is there anything obvious I am doing wrong here for my specific environment?

**Comment by gth828r** [comment]
I'll keep poking around and trying out different parameters today and I'll follow up if I find anything interesting.

**Comment by gth828r** [comment]
One nugget that I should have shared before... this is my profile:
```json
{
    "module_to_stage_map": [0, 1, 1],
    "stage_to_rank_map": {"0": [0, 1, 2], "1": [3]}
}
```

**Comment by gth828r** [comment]
Also, this is my generated `stage1.py` for the 4 GPU vgg16 model:
```py3
import torch


class Stage1(torch.nn.Module):
    def __init__(self):
        super(Stage1, self).__init__()
        self.layer1 = torch.nn.Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.layer2 = torch.nn.ReLU(inplace=True)
        self.layer3 = torch.nn.Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.layer4 = torch.nn.ReLU(inplace=True)
        self.layer5 = torch.nn.Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.layer6 = torch.nn.ReLU(inplace=True)
        self.layer7 = torch.nn.MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
        self.layer8 = torch.nn.Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.layer9 = torch.nn.ReLU(inplace=True)
        self.layer10 = torch.nn.Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.layer11 = torch.nn.ReLU(inplace=True)
        self.layer12 = torch.nn.Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.layer13 = torch.nn.ReLU(inplace=True)
        self.layer14 = torch.nn.MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
        self.layer17 = torch.nn.Linear(in_features=25088, out_features=4096, bias=True)
        self.layer18 = torch.nn.ReLU(inplace=True)
        self.layer19 = torch.nn.Dropout(p=0.5)
        self.layer20 = torch.nn.Linear(in_features=4096, out_features=4096, bias=True)
        self.layer21 = torch.nn.ReLU(inplace=True)
        self.layer22 = torch.nn.Dropout(p=0.5)
        self.layer23 = torch.nn.Linear(in_features=4096, out_features=1000, bias=True)
        self._initialize_weights()

    def _initialize_weights(self):
        for m in self.modules():
            if isinstance(m, torch.nn.Conv2d):
                torch.nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
                if m.bias is not None:
                    torch.nn.init.constant_(m.bias, 0)
            elif isinstance(m, torch.nn.BatchNorm2d):
                torch.nn.init.constant_(m.weight, 1)
                torch.nn.init.constant_(m.bias, 0)
            elif isinstance(m, torch.nn.Linear):
                torch.nn.init.normal_(m.weight, 0, 0.01)
                torch.nn.init.constant_(m.bias, 0)

    def forward(self, input0):
        out0 = input0.clone()
        out1 = self.layer1(out0)
        out2 = self.layer2(out1)
        out3 = self.layer3(out2)
        out4 = self.layer4(out3)
        out5 = self.layer5(out4)
        out6 = self.layer6(out5)
        out7 = self.layer7(out6)
        out8 = self.layer8(out7)
        out9 = self.layer9(out8)
        out10 = self.layer10(out9)
        out11 = self.layer11(out10)
        out12 = self.layer12(out11)
        out13 = self.layer13(out12)
        out14 = self.layer14(out13)
        out15 = out14.size(0)
        out16 = out14.view(out15)
        out17 = self.layer17(out16)
        out18 = self.layer18(out17)
        out19 = self.layer19(out18)
        out20 = self.layer20(out19)
        out21 = self.layer21(out20)
        out22 = self.layer22(out21)
        out23 = self.layer23(out22)
        return out23
```

In both this model and the alexnet model that was throwing a similar error, it is a call to `view` which is ultimately throwing the error.

**Comment by deepakn94** [comment]
Interesting, it seems like this might be related to #1. I am looking at my existing generated code for VGG-16, and it seems like [this line](https://github.com/msr-fiddle/pipedream/blob/master/runtime/image_classification/models/vgg16/gpus%3D4/stage1.py#L51) is different. In particular, `out18 = out16.view(out17, -1)`. Can you see if that changes things? Let me dig a bit to figure out why this is being code generated differently now.

**Comment by gth828r** [comment]
Adding in the additional -1 parameter to the view call in my generated code got me past the issue.  Nice suggestion!  I am now running out of memory, but that sounds like a separate problem which is probably my own to sort through...

**Comment by deepakn94** [comment]
Follow up to this -- what version of `torchvision` are you using?

**Comment by gth828r** [comment]
It looks like I am using torchvision 0.2.1, which is I believe the current default.  I built the docker image yesterday, and FWIW I did not make any manual changes to the conda packages.

**Comment by deepakn94** [comment]
Can you try the workflow again -- I think I've fixed this issue with 23632d2. Thanks!

**Comment by gth828r** [comment]
I updated to the latest and reran the optimize steps over a previous profiled input, but I am seeing a similar issue:
```
# python main_with_runtime.py --module models.alexnet.gpus=4 -b 256 --data_dir /mnt --master_addr 127.0.0.1 --config_path models/alexnet/gpus=4/hybrid_conf.json --distributed_backend gloo -v 1 --rank 0 --local_rank 0 --epochs 1
Traceback (most recent call last):
  File "main_with_runtime.py", line 578, in <module>
    main()
  File "main_with_runtime.py", line 149, in main
    output_tensors = stage(*tuple(input_tensors))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/pipedream/runtime/image_classification/models/alexnet/gpus=4/stage1.py", line 20, in forward
    out2 = out0.view(out1)
RuntimeError: shape '[256]' is invalid for input of size 2359296
```

Here is the relevant function definition in my stage1.py:
```python
    def forward(self, input1):
        out0 = input1.clone()
        out1 = out0.size(0)
        out2 = out0.view(out1)
        out3 = self.layer3(out2)
        out4 = self.layer4(out3)
        out5 = self.layer5(out4)
        out6 = self.layer6(out5)
        out7 = self.layer7(out6)
        out8 = self.layer8(out7)
        out9 = self.layer9(out8)
        return out9
```

Please let me know if I can provide you any other inputs to help with debugging.  This is not urgent on my end anymore since you provided a workaround, but I can easily send you what I've generated on my system if it is helpful.

**Comment by deepakn94** [comment]
Ah, the updated code was in the profiler (so you will need to rerun the profiler to see updated behavior).

**Comment by gth828r** [comment]
Gotcha, sorry!  I should have looked at what code actually changed.  When I run the profiler now, I get the following:
```
# CUDA_VISIBLE_DEVICES=0 python main.py -a alexnet -b 256 --data_dir /mnt
=> creating model 'alexnet'
Collecting profile...
Traceback (most recent call last):
  File "main.py", line 578, in <module>
    main()
  File "main.py", line 266, in main
    per_layer_times, data_time = profile_train(train_loader, model, criterion, optimizer)
  File "main.py", line 408, in profile_train
    data_timestamps, opt_step_timestamps)
  File "../torchmodules/torchprofiler/generate_json.py", line 56, in generate_json
    blob['ts'] = iteration_timestamps[i]['start']
IndexError: list index out of range
```

**Comment by deepakn94** [comment]
I am not able to reproduce this on my end. Anyway, `generate_json` doesn't need to be called, so I removed all calls to it in 0ecfb02fc4d60d606bb8634eaad134e8c99760ab. Let me know if you still face issues.

**Comment by gth828r** [comment]
Your latest change fixed both the last problem I had as well as the original reported issue.  I think this one can be closed now.  Thanks!
