### ISSUE TITLE
optimizer got an empty parameter list when rank=1

### ISSUE THREAD

**Issue by Hyaloid** [msr-fiddle/pipedream#79]
Hi, I was trying to train vgg16 with the configs below:

- models.vgg16.gpus=2
- mp_conf.json

with command:
```
CUDA_VISIBLE_DEVICES=0,2 python -m torch.distributed.launch main_with_runtime.py --module models.vgg16.gpus=2 -b 4 --data_dir /home --rank 0 --config_path /mnt/runtime/image_classification/models/vgg16/gpus=2/mp_conf.json --master_addr localhost --local_rank 0 --distributed_backend gloo
CUDA_VISIBLE_DEVICES=0,2 python -m torch.distributed.launch main_with_runtime.py --module models.vgg16.gpus=2 -b 4 --data_dir /home --rank 1 --config_path /mnt/runtime/image_classification/models/vgg16/gpus=2/mp_conf.json --master_addr localhost --local_rank 1 --distributed_backend gloo
```

but I got an error when `rank = 1`, which says:
```
Traceback (most recent call last):
  File "main_with_runtime.py", line 587, in <module>
    main()
  File "main_with_runtime.py", line 231, in main
    macrobatch=args.macrobatch)
  File "../sgd.py", line 23, in __init__
    macrobatch=macrobatch,
  File "../optimizer.py", line 41, in __init__
    master_parameters, **optimizer_args)
  File "/opt/conda/lib/python3.6/site-packages/torch/optim/sgd.py", line 64, in __init__
    super(SGD, self).__init__(params, defaults)
  File "/opt/conda/lib/python3.6/site-packages/torch/optim/optimizer.py", line 45, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list
```
I printed `master_parameters` when rank is 1, and it shows an empty list. However, the list is not empty when rank is 0. I can't figure out why the parameter list is empty. It would be so appreciated if anyone could help.

**Comment by Hyaloid** [comment]
I modified `"module_to_stage_map"` in `mp_conf.json` from `[0, 1, 1]` to `[0, 0, 1]`. Using this config, only `CrossEntropyLoss()` is training on stage1. As `CrossEntropyLoss()` contains no parameter, the parameter list is empty.
